package com.colegiosantacecilia.siwcspringjava.GUI;

import com.colegiosantacecilia.siwcspringjava.Metodos.Hilos.HiloCloseSpringApplication;
import com.colegiosantacecilia.siwcspringjava.Metodos.Hilos.HiloClosingService;
import com.colegiosantacecilia.siwcspringjava.Metodos.Hilos.HiloSpringApplication;
import com.colegiosantacecilia.siwcspringjava.Metodos.Hilos.HiloStartingService;
import java.awt.Color;
import org.springframework.context.ConfigurableApplicationContext;

/**
 *
 * @author Sebastian Villamizar
 *
 */
public class appSIWC_SJApplication extends javax.swing.JFrame {

    appSIWC_SJApplicationError applicationError;
    ConfigurableApplicationContext cac;
    private boolean statusStartedStopped;

    public appSIWC_SJApplication() {
        initComponents();
        lbLoading.setVisible(false);
        txtLb.setVisible(false);
        setAlwaysOnTop(true);
        pack();
        applicationError = new appSIWC_SJApplicationError();
    }

    public void startingService() {
        System.out.println("StartingService");
        applicationError.dispose();
        this.txtLb.setForeground(Color.BLACK);
        setLocationRelativeTo(null);
        txtLb.setText("STARTING SERVICE");
        lbLoading.setVisible(true);
        txtLb.setVisible(true);
        btnRunS.setEnabled(false);
        lblconClose.setEnabled(false);
        pack();
        statusStartedStopped = true;
    }

    public void closingService() {
        System.out.println("PARAR SERVICE");
        txtLb.setForeground(new Color(255, 51, 51, 255));
        txtLb.setText("CLOSING SERVICE");
        lbLoading.setVisible(true);
        txtLb.setVisible(true);
        btnRunS.setEnabled(false);
        pack();
    }

    public void serviceStarted(ConfigurableApplicationContext context) {
        cac = context;
        btnRunS.setEnabled(true);
        lbLoading.setVisible(false);
        pack();
        txtLb.setForeground(new Color(102, 255, 102, 255));
        txtLb.setText("SERVICE STARTED");
        btnRunS.setText("STOP SERVICE");
    }

    public void serviceClosed() {
        cac.close();
        btnRunS.setText("RESTART SERVICE");
        btnRunS.setEnabled(true);
        lblconClose.setEnabled(true);
        txtLb.setVisible(false);
        statusStartedStopped = false;
        txtLb.setText("");
        lbLoading.setVisible(false);
        pack();
    }

    public void serviceStoped(Exception e) {
        lbLoading.setVisible(false);
        btnRunS.setEnabled(true);
        lblconClose.setEnabled(true);
        pack();
        statusStartedStopped = false;
        txtLb.setForeground(new Color(239, 103, 103, 255));
        txtLb.setText("SERVICE STOPED");
        setLocation(getX(), 120);
        applicationError.setLocationRelativeTo(null);
        applicationError.setTxtAreaError(e.getMessage());
        applicationError.setTxtLbError(e.getCause().getMessage());
        applicationError.setLocation();
        applicationError.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRunS = new javax.swing.JButton();
        lblconClose = new javax.swing.JLabel();
        lblIcon1 = new javax.swing.JLabel();
        txtLb = new javax.swing.JLabel();
        lbLoading = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btnRunS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRunS.setText("RUN SERVICE");
        btnRunS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRunS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunSActionPerformed(evt);
            }
        });

        lblconClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblconClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/close.png"))); // NOI18N
        lblconClose.setPreferredSize(new java.awt.Dimension(45, 45));
        lblconClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblconCloseMouseClicked(evt);
            }
        });

        lblIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/negativo.png"))); // NOI18N
        lblIcon1.setPreferredSize(new java.awt.Dimension(45, 45));
        lblIcon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIcon1MouseClicked(evt);
            }
        });

        txtLb.setBackground(new java.awt.Color(255, 255, 255));
        txtLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLb.setForeground(new java.awt.Color(102, 255, 102));
        txtLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbLoading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/gifTresPuntosCargandoM.gif"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SERVICE CSC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblconClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnRunS, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLoading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblconClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnRunS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLb, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRunSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunSActionPerformed
        if (btnRunS.getText().equals("STOP SERVICE") && txtLb.getText().equals("SERVICE STARTED")) {
            HiloClosingService hiloClosingService = new HiloClosingService(this);
            hiloClosingService.start();
            HiloCloseSpringApplication hiloCloseSpringApplication = new HiloCloseSpringApplication(this, hiloClosingService);
            hiloCloseSpringApplication.start();
        } else {
            HiloStartingService hiloStartingService = new HiloStartingService(this);
            hiloStartingService.start();
            HiloSpringApplication hiloSpringApplication = new HiloSpringApplication(this, hiloStartingService);
            hiloSpringApplication.start();
        }

    }//GEN-LAST:event_btnRunSActionPerformed

    private void lblconCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblconCloseMouseClicked
        if (!statusStartedStopped) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblconCloseMouseClicked

    private void lblIcon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcon1MouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_lblIcon1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appSIWC_SJApplication.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appSIWC_SJApplication.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appSIWC_SJApplication.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appSIWC_SJApplication.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new appSIWC_SJApplication().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRunS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbLoading;
    private javax.swing.JLabel lblIcon1;
    private javax.swing.JLabel lblconClose;
    private javax.swing.JLabel txtLb;
    // End of variables declaration//GEN-END:variables
}
